### ISSUE TITLE
After the focus has changed, on the "new" unfocused monitor waybar still hidden.

### ISSUE THREAD

**Issue by n-connect** [Direwolfesp/auto-waybar-cpp#3]
As per #1 , new function and new behaviours implemented.

Within the `-m focused` mode it start to work as planned:
- the focused monitor's waybar gets hidden, other's not

But after focus change:
- the new monitor which got the focuse its waybar gets hidden -> good
- but the other, noww unfocused monitor's waybar stays hidden as well.

If I understand well, the unfocused monitor's waybar should stay or should get shown.

Details/logs in the 8 post of #1.

**Comment by Direwolfesp** [comment]
Could you provide an output of `hyprctl monitors all` so I can see what's being parsed?

**Comment by n-connect** [comment]
Sure, it a bit excessive big list I've cut out serial numbers and such:

```bash
Monitor eDP-1 (ID 0):
        1920x1080@60.03300 at 3440x0
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 0 0 0
        scale: 1.50
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 1920x1080@60.03Hz

Monitor DP-2 (ID 1):
        3440x1440@59.97300 at 4720x0
        active workspace: 2 (2)
        special workspace: 0 ()
        reserved: 0 34 0 0
        scale: 1.00
        transform: 0
        focused: no
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 3440x1440@59.97Hz
```

hyprctl.conf snippet:
```
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,preferred,3440x0,1.5
monitor=DP-2,preferred,auto,auto
```

**Comment by Direwolfesp** [comment]
Hmm, so you have eDP-1 at the right, and the 4k one on the left right? If that's correct why don't you try setting eDP-1 at 0x0, and DP-2 at auto-left?

Because you are setting the 4k one at x: 1920/1.5 + 3440 = 4720, which has sense because of the eDP-1 scaling. But I don't get the other one x pos xd.

**Comment by n-connect** [comment]
Hey,

Well, I've just tried various versions from the wiki/reddit, when finally I got one without overlapping app windows on the common edge of the 2 monitors (changing f-scale constantly). Now I've changed eDP-1 to 0x0 and actually, it gives the same result on hyprland 0.47.2 :D 
I have to point out I've moved from a native packages quite old version 0.41.x . Moved latest release 0.47.2 beginning last month, so I'm sure there were tons of various fixes some around multi-monitor handling and I've just not followed-up yet - until now.

So now eDP-1 0x0 DP2 on the right edge, and fractional scale of eDP-1 is 1.25 (nice sunny day -> moving back and forth between 1.25-1.5)
Edit: fun fact I can still oversize a window in 0.47.2, eg. the resizing mouse pointer goes outside of the seeable area of current monitor. I've thought its a bug in older version, but no. When I'm on multi-monitor I can see the resizing mouse in the other monitor, in standalone monitor it (mouse pointer with the window border/corner) just disappear. I would think a window should not be bigger than its monitor size/resolution. Maybe its something around the defaultl tiling behavior - which I'm not using bc of the small screen. Its only good on big monitors IMHO.

```bash
autowaybar -m focused -t 30
[LOG] Monitor named eDP-1 found in x: 0, width: 1920.
[LOG] Monitor named DP-2 found in x: 1536, width: 3440.
[INFO] Waybar config file found in '/home/<username>/.config/waybar/config.jsonc'
[INFO] Launching Hide Focused Mode
[INFO] Mon: DP-2 needs to be hidden.
[LOG] Updating
[LOG] New update: [
        "eDP-1"
][INFO] Reloading PID: 2552720
[INFO] Mouse (2238,1148)
[INFO] Mouse (2238,1148)
```

The behaviour has not changed though:
- after focus change the new DP2 waybar get hidden, from fixed,
- **but the eDP-1 based waybar stay hidden,**
- unhiding the new focused DP2 unhide the eDP1 -> but based on it is just one instance of waybar and it is controlled with SIGUSR -s that is how it should work

Let me know, if you need anything else

```bash
hyprctl monitors all
Monitor eDP-1 (ID 0):
        1920x1080@60.03300 at 0x0
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 0 0 0
        scale: 1.25
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: false                                                                                                                    solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 1920x1080@60.03Hz

Monitor DP-2 (ID 1):
        3440x1440@59.97300 at 1536x0
        active workspace: 2 (2)
        special workspace: 0 ()
        reserved: 0 35 0 0
        scale: 1.00
        transform: 0
        focused: no
        dpmsStatus: 1
        vrr: false
        solitary: 0
        activelyTearing: false
        directScanoutTo: 0
        disabled: false
        currentFormat: XRGB8888
        mirrorOf: none
        availableModes: 3440x1440@59.97Hz
```

**Comment by Direwolfesp** [comment]
Okai, i think i know what might be happening. I forgot to take your full hd monitor width as the (Width / Scale) in your case (1920/1.25 = 1536). That's why it can't detect what monitor you are in.

From Hyprland Wiki:  
> The position is calculated with the scaled (and transformed) resolution, meaning if you want your 4K monitor with scale 2 to the left of your 1080p one, you’d use the position 1920x0 for the second screen (3840 / 2). If the monitor is also rotated 90 degrees (vertical), you’d use 1080x0.

I'll try to fix it when I get home.

**Comment by n-connect** [comment]
Yepp, when one is using scaling, the original resolution mapped(???) into a different one:
- 1080p /w 1.5 scale 1280x720,
- 1080p /w 1.25 scale 1536x864.

So the code should move from "resolution" to "resolution/scale" in m_output.begin-m_output.end at line 242(?). That will give the correct numbers for any screen -> its best use this for every monitor, no exception handling needed. Around here within [getMonitorsInfo](https://github.com/Direwolfesp/auto-waybar-cpp/blob/c4b8151f4559a831db2dcf376cb348004bc5a023/src/waybar.cpp#L58)

_In parallel I realized, its the -m focused mode that mess up my waybar config :D Just now I've manually searched and moved the parameters in the config.jsonc file 3rd or 4th time since we test. This last time, I've actually lost one line completely:, the one with says which monitors it should be shown. So the error was seen really fast. Maybe it better to be a separate issue, let me know._

_I'm not really got the logic for first sight at [line 288](I'm not really got the logic for first sight at [line 288]([[url]](https://github.com/Direwolfesp/auto-waybar-cpp/blob/c4b8151f4559a831db2dcf376cb348004bc5a023/src/waybar.cpp#L288))_

_I believe its around this `truncateFile line` in [waybar.cpp](https://github.com/Direwolfesp/auto-waybar-cpp/blob/c4b8151f4559a831db2dcf376cb348004bc5a023/src/waybar.cpp#L292), I don't know, maybe a backup copy at initialization should help, however there's plenty:_
- waybar config read into "file",
- than file goes into JSON "config",
- if there's more than one "config", it drops it,
- than comes the manipulation of the output, depending on what exist in "config" vs. actual
- save original as "initial_output"
- "o_file" offstream created
- truncate happens against "o_file"

Also just run into shell scripts which are doing this kind of mouse pointer polling and run SIGUSR1 / SIGUSR2 on waybar's process. those evolved into event-driven  from polling. Food for thought :)

**Comment by Direwolfesp** [comment]
> So the code should move from "resolution" to "resolution/scale" in m_output.begin-m_output.end at line 242(?). That will give the correct numbers for any screen -> its best use this for every monitor, no exception handling needed. Around here within

**Comment by Direwolfesp** [comment]
FFF i missclicked XDD

**Comment by Direwolfesp** [comment]
> So the code should move from "resolution" to "resolution/scale" in m_output.begin-m_output.end at line 242(?). That will give the correct numbers for any screen -> its best use this for every monitor, no exception handling needed. Around here within [getMonitorsInfo](https://github.com/Direwolfesp/auto-waybar-cpp/blob/c4b8151f4559a831db2dcf376cb348004bc5a023/src/waybar.cpp#L58)

Okai, i pushed in commit 5c0a2b2.

**Comment by Direwolfesp** [comment]
> I'm not really got the logic for first sight at [line 288](I'm not really got the logic for first sight at line 288

So, in the while loop, i check for the state of all the monitors and update the bool hidden accordingly, if something has changed, i togle the bool flag need_reload to true, so it gets reloaded.

> In parallel I realized, its the -m focused mode that mess up my waybar config :D Just now I've manually searched and moved the parameters in the config.jsonc file 3rd or 4th time since we test. This last time, I've actually lost one line completely:, the one with says which monitors it should be shown. So the error was seen really fast. Maybe it better to be a separate issue, let me know.
I believe its around this truncateFile line in [waybar.cpp](https://github.com/Direwolfesp/auto-waybar-cpp/blob/c4b8151f4559a831db2dcf376cb348004bc5a023/src/waybar.cpp#L292), I don't know, maybe a backup copy at initialization should help, however there's plenty:
> 
> waybar config read into "file",
> than file goes into JSON "config",
> if there's more than one "config", it drops it,
> than comes the manipulation of the output, depending on what exist in "config" vs. actual
> save original as "initial_output"
> "o_file" offstream created
> truncate happens against "o_file"

Hmm, idk why it happened to you, maybe i should get rid of initial_outputs, and create an additional json_object with the orignal config, and in the // restore original config   just set that

**Comment by Direwolfesp** [comment]
> Also just run into shell scripts which are doing this kind of mouse pointer polling and run SIGUSR1 / SIGUSR2 on waybar's process. those evolved into event-driven from polling. Food for thought :)

Ye i also saw that shell script that just react to events. It would be cool to implement everything with sockets because that would be more clean and also efficient. And more important, as a learning tool, as that was my initial idea with this repo ^^. However, i think if we want to redesign everything with sockets we should make another branch and some Classes / design pattern decision, as i made almost everything the spaghetti way xd.

**Comment by n-connect** [comment]
> > Also just run into shell scripts which are doing this kind of mouse pointer polling and run SIGUSR1 / SIGUSR2 on waybar's process. those evolved into event-driven from polling. Food for thought :)
> 
> Ye i also saw that shell script that just react to events. It would be cool to implement everything with sockets because that would be more clean and also efficient. And more important, as a learning tool, as that was my initial idea with this repo ^^. However, i think if we want to redesign everything with sockets we should make another branch and some Classes / design pattern decision, as i made almost everything the spaghetti way xd.

And I also need to learn to add some c++ code not just talking from the sideline :)

Anyway, thank for the quick change I've read the code change. Unfortunately the issue has not fixed -> at least on my notebook. If its working for you, we should compare "notes" our hyprland and waybar config.
In general, if its and error for you to, than it seems I way wrong with my idea around the scale, as an answer for your resolution idea. OR there is another place need to be modified to achieve unhiding after focus change.

The plus one issue: my waybar config messed up again testing `-m focused`. As far as I know its regular:
- generic values first,
- then modules to show in left/middle/right,
- than modules configs + custom-modules config
- plus the output

So, if you say there's a best place for `output` part, like - idk - end of config, let me know :D 

The first section torn out from its place: from line 3. Also I have no width setting -> cause of the fractional scale/multimonitor use 

```
        "layer" : "top", // Waybar at top layer    
        "position" : "top", // Waybar position (top|bottom|left|right)    
        "height" : 30, // Waybar height (to be removed for auto height)    
        // "width": 1280, // Waybar width    
        "spacing" : 2, // Gaps between modules (4px)    
        "output" :     
        [    
                "eDP-1",             
                "DP-2"     
        ],                           
        // Choose the order of the modules    
        "modules-left" :
```
Edit2: added the full log of this round's tests: 
- 1st start with one monitor, then add a second,
- 2nd start with two monitors,

[autowaybar.log](https://github.com/user-attachments/files/19075856/autowaybar.log)

**Comment by Direwolfesp** [comment]
Can you try with new commit ? d319f92

**Comment by n-connect** [comment]
Bullseye! Reading the scale value into `.asFloat` did the trick -> even though we counted with fix numbers it could be a non-int result...

_Edit: ohh almost forgot... The fallback works, but the `-m focused` won't recognize a later attached new monitor, to be able to act as focused mode yet. In other words: there's no fallback from the fallback yet in the code. With that the circle would be complete on `-m focused`_

On the other side of the issue: I can confirm the `-m focused` do always the same kind of mixture within my waybar's config.jsonc :D 

The main lines shredded around the config line by line, the modules order always split the same way and the modules configuration have always the same shift around -> may some kind of serialization issue.

I can share and original versus messed up if it helps :D 

So titular issue fixed, we can close it. The new-connected one should earn it own one?

**Comment by Direwolfesp** [comment]
> Bullseye! Reading the scale value into .asFloat did the trick -> even though we counted with fix numbers it could be a non-int result...

Good to hear it works!, the int result would only matter for sub-pixel precision i think.

> On the other side of the issue: I can confirm the -m focused do always the same kind of mixture within my waybar's config.jsonc :D
> The main lines shredded around the config line by line, the modules order always split the same way and the modules configuration have always the same shift around -> may some kind of serialization issue.

Yeah the order of the config might get altered but that does not change how the json gets parsed etc.. And i dont have much control about that, im using  jsoncpp (the one that waybar uses btw). But yeah, if you like your config to be in order, it can get  a bit annoying. I have just get used to it personally xd.

> Edit: ohh almost forgot... The fallback works, but the -m focused won't recognize a later attached new monitor, to be able to act as focused mode yet. In other words: there's no fallback from the fallback yet in the code. With that the circle would be complete on -m focused
> So titular issue fixed, we can close it. The new-connected one should earn it own one?

Yes, that should be in the TODO list for now. That might need a new issue and a branch maybe. Because as I said earlier that is gonna be a little more complicated. I also found waybar itselft not behaving very good with (un)plugging monitors on the fly, I almost always end up reloading it xd. 

So I'll closed one as fixed in d319f92
